pokemoncards/main_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('',views.home, name='home'),
    path('about/',views.about, name='about'),
    path('pokemon/',views.pokemon_index,name='index'),
    path('pokemon/<int:pokemon_id>/',views.pokemon_details,name='details'),
    path('pokemon/create/',views.PokemonCreate.as_view(),name='pokemon_create'),
    path('pokemon/<int:pk>/update/',views.PokemonUpdate.as_view(),name='pokemon_update'),
    path('pokemon/<int:pk>/delete/',views.PokemonDelete.as_view(),name='pokemon_delete'),
    path('pokemon/<int:pokemon_id>/add_purchase/',views.add_purchase,name='add_purchase'),
    
    path('accessory/',views.AccessoryList.as_view(), name= 'accessory_index'),
    path('accessory/<int:pk>/',views.AccessoryDetail.as_view(), name= 'accessory_detail'),
    path('accessory/create/',views.AccessoryCreate.as_view(), name= 'accessory_create'),
    path('accessory/<int:pk>/update/',views.AccessoryUpdate.as_view(), name= 'accessory_update'),
    path('accessory/<int:pk>/delete',views.AccessoryDelete.as_view(), name= 'accessory_delete'),
]

pokemoncards/pokemoncards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main_app.urls'))
]

pokemoncards/main_app/models.py
from django.db import models
from django.urls import reverse
RARITY=(
    ('R','Rare'),
    ('SR','Super Rare'),
    ('UR','Ultra Rare')
)

class Accessory(models.Model):
    name= models.CharField(max_length=50)
    color= models.CharField(max_length=20)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('accessory_detail',kwargs={'pk':self.id})
    
    
class Pokemon(models.Model):
    name=models.CharField(max_length=100)
    type=models.CharField(max_length=100)
    power=models.IntegerField()
    weakness=models.CharField(max_length=100)
    image= models.ImageField(upload_to='main_app/static/uploads',default='')
    accessories= models.ManyToManyField(Accessory) 
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('details',kwargs={'pokemon_id':self.id})
# Create your models here.

class Purchase(models.Model):
    date=models.DateField()
    rarity=models.CharField(max_length=3, choices=RARITY, default=RARITY[0][0])
    pokemon= models.ForeignKey(Pokemon,on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.pokemon.name} {self.get_rarity_display()} on {self.date}"

pokemoncards/main_app/forms.py
from django.forms import ModelForm
from .models import Purchase

class PurchaseForm(ModelForm):
    class Meta:
        model=Purchase
        fields=['date','rarity']

pokemoncards/main_app/views.py
from django.shortcuts import render, redirect
from .models import Pokemon, Accessory
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import PurchaseForm
# Create your views here.
class PokemonCreate(CreateView):
    model=Pokemon
    fields=['name','type','power','weakness','image']

class PokemonUpdate(UpdateView):
    model=Pokemon
    fields=['name','type','power','weakness','image']

class PokemonDelete(DeleteView):
    model=Pokemon
    success_url='/pokemon/'

def home(request):
    return render(request,'home.html')
def about(request):
    return render(request,'about.html')
def pokemon_index(request):
    pokemons= Pokemon.objects.all()
    return render(request,'pokemon/index.html',{'pokemons':pokemons})
def pokemon_details(request,pokemon_id):
    pokemon= Pokemon.objects.get(id=pokemon_id)
    purchase_form=PurchaseForm()
    return render(request,'pokemon/details.html',{'pokemon':pokemon, 'purchase_form':purchase_form})
def add_purchase(request,pokemon_id):
    form = PurchaseForm(request.POST)
    if form.is_valid():
        new_purchase=form.save(commit=False)
        new_purchase.pokemon_id=pokemon_id
        new_purchase.save()
        return redirect('details',pokemon_id=pokemon_id)


#Accessory CBVs views

class AccessoryList(ListView):
    model = Accessory
class AccessoryDetail(DetailView):
    model=Accessory
class AccessoryCreate(CreateView):
    model=Accessory
    fields= '__all__' # this means all field in the model (shortcut)

class AccessoryUpdate(UpdateView):
    model=Accessory
    fields='__all__'

class AccessoryDelete(DeleteView):
    model=Accessory
    success_url='/accessory/'

pokemoncards/main_app/templates/about.html
{% extends 'base.html'%}
{%block content%}

<h1>About Page</h1>
{%endblock%}

pokemoncards/main_app/templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pokemon Cards App</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-datepicker@1.10.0/dist/css/bootstrap-datepicker.min.css">
<script src="https://cdn.jsdelivr.net/npm/bootstrap-datepicker@1.10.0/dist/js/bootstrap-datepicker.min.js"></script>
</head>
<body>

    <nav  class="p-3 m-0 border-0 bd-example m-0 border-0">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'home'%}active{%endif%} " href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'about'%}active{%endif%}" href="{% url 'about' %}">about</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'index'%}active{%endif%}" href="{% url 'index' %}">Pokemon List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'details'%}active{%endif%}">Pokemon Details</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'pokemon_create'%}active{%endif%}" href="{% url 'pokemon_create' %}">Add Pokemon Card</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'accessory_create'%}active{%endif%} " href="{% url 'accessory_create' %}">Add Accessory</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'accessory_index'%}active{%endif%} " href="{% url 'accessory_index' %}">View All Accessory</a>
      </li>      
    </ul>
    </nav>
<main class="flex-fill">
<div class="container-fluid h-100">
    <div class="p-4 bg-white border rounded shadow-sm h-100">
    {%block content%}
    {%endblock%}
    </div>

</div>


</main>
<footer class="bg-dark text-white text-center py-3 mt-auto">
    <p class="mb-0">© 2025 Pokemon Cards</p>
</footer>

</body>
</html>

pokemoncards/main_app/templates/home.html
{% extends 'base.html'%}
{%block content%}

<h1>Welcome to Pokemon Cards App</h1>
{% endblock %}

pokemoncards/main_app/templates/main_app/accessory_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h1>Delete Accessory</h1>
  <h4>Are you sure you want to delete <span>{{ object.name }}</span>?</h4>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'accessory_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

pokemoncards/main_app/templates/main_app/accessory_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Toy Details</h1>
<div>
  <div>
    <div>
      <div>
        <span>{{ accessory.name }}</span>
        <p>Color: {{ accessory.color }}</p>
      </div>
      <div>
        <a href="{% url 'accessory_update' accessory.id %}">Edit</a>
        <a href="{% url 'accessory_delete' accessory.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

pokemoncards/main_app/templates/main_app/accessory_form.html
{% extends 'base.html' %}
{% block content %}
  {% if object %}
    <h1>Edit <span>{{object.name}}</span></h1>
  {% else %}
    <h1>Add Accessory</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

pokemoncards/main_app/templates/main_app/accessory_list.html
{%extends 'base.html'%}
{%block content%}

<h1>Accessory List</h1>

{% for  accessory in accessory_list %}
<a href="{% url 'accessory_detail' accessory.id %}">
    <div>
        <div>
            <span>{{accessory.name}}</span>
            <p>Color : {{accessory.color}}</p>
        </div>
    </div>
</a>
{%endfor%}
{%endblock%}

pokemoncards/main_app/templates/main_app/pokemon_confirm_delete.html
{% extends 'base.html'%}
{%block content%}

<h1>Delete Pokemon</h1>
<h4>Are you sure you want to delete <span>{{object.name|upper}}</span>?</h4>
<form action="" method="post">
{%csrf_token%}
<input type="submit" value="Yes - Delete">
<a href="{% url 'details' pokemon.id %}">Cancel</a>


</form>


{%endblock%}

pokemoncards/main_app/templates/main_app/pokemon_form.html
{% extends 'base.html'%}

{% block content%}
{% if object%}
<h1>Edit <span>{{object.name}}</span></h1>
{%else%}
<h1>Add Pokemon Card</h1>
{%endif%}

<form action="" method="post" enctype="multipart/form-data">
{%csrf_token%}
<table>
    {{form.as_table}}
</table>
<input type="submit" value="submit!">
<a href="{% url 'index'%}">Cancel</a>

</form>


{%endblock%}

pokemoncards/main_app/templates/pokemon/details.html
{% extends 'base.html' %}
{% block content %}
<div style="display: flex; gap: 10rem;">

    <div class="card" style="width: 18rem;">

        <div class="card" style="width: 18rem;">
            {% load static %}
            <img src="{% static pokemon.image|cut:'main_app/static/' %}" class="card-img-top" alt="Pokemon Image">
        </div>

        <div>
            <p>Name: {{ pokemon.name }} </p>
            <p>Type: {{ pokemon.type }}</p>
            <p>Weakness: {{ pokemon.weakness }}</p>
            <p>Power: {{ pokemon.power }}</p>
        </div>

        <a href="{% url 'pokemon_update' pokemon.id %}" class="btn btn-warning btn-sm mt-2">Edit</a>
        <a href="{% url 'pokemon_delete' pokemon.id %}" class="btn btn-danger btn-sm mt-2">Delete</a>
    </div>

    <div>
        {% load widget_tweaks %}
        <form action="{% url 'add_purchase' pokemon.id %}" method="post" class="mt-3">
            {% csrf_token %}

            <div class="mb-3">
                <label for="id_date" class="form-label">Date</label>
                {{ purchase_form.date|add_class:"form-control" }}
            </div>

            <div class="mb-3">
                <label for="id_rarity" class="form-label">Rarity</label>
                {{ purchase_form.rarity|add_class:"form-select" }}
            </div>

            <button type="submit" class="btn btn-primary">Add Purchase</button>
        </form>
    </div>

    <div class="mt-4">
        <table class="table table-striped">
            <thead class="table-dark">
                <tr>
                    <th>Date</th>
                    <th>Rarity</th>
                </tr>
            </thead>
            <tbody>
                {% for purchase in pokemon.purchase_set.all %}
                <tr>
                    <td>{{ purchase.date|date:"M d, Y" }}</td>
                    <td>{{ purchase.get_rarity_display }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<script>
  $(document).ready(function(){
      $('#id_date').datepicker({
          format: 'yyyy-mm-dd',
          autoclose: true,
          todayHighlight: true
      });
  });
</script>
{% endblock %}

pokemoncards/main_app/templates/pokemon/index.html
{%extends 'base.html'%}

{% block content%}
<div style="display: flex; flex-wrap: wrap; justify-content: space-between;">
{% for pokemon in pokemons%}

<div class= "card" style="width: 18rem;" >

    <div class="card" style="width: 18rem;">
        {%load static%}
    <img src="{% static pokemon.image|cut:'main_app/static/'%}" class="card-img-top" width="100px" height="200px" alt="Pokemon Image">
    </div>

    <div style="justify-items: center;" >
    <h4 >{{pokemon.name}} </h4>   
    </div> 
    <div style="align-self: center;" >
        <a href="{% url 'details' pokemon.id%}">View more Details</a>
    </div>
</div>

{%endfor%}

</div>
{%endblock%}